
package com.wondersgroup.mydemo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JawTbsServiceImplService", targetNamespace = "http://service.webService.tcm.wondersgroup.com/", wsdlLocation = "http://10.10.13.122:8080/tcm/cxf/SoaWsPublisher?wsdl")
public class JawTbsServiceImplService
    extends Service
{

    private final static URL JAWTBSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JAWTBSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName JAWTBSSERVICEIMPLSERVICE_QNAME = new QName("http://service.webService.tcm.wondersgroup.com/", "JawTbsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.10.13.122:8080/tcm/cxf/SoaWsPublisher?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JAWTBSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        JAWTBSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public JawTbsServiceImplService() {
        super(__getWsdlLocation(), JAWTBSSERVICEIMPLSERVICE_QNAME);
    }

    public JawTbsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAWTBSSERVICEIMPLSERVICE_QNAME, features);
    }

    public JawTbsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, JAWTBSSERVICEIMPLSERVICE_QNAME);
    }

    public JawTbsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAWTBSSERVICEIMPLSERVICE_QNAME, features);
    }

    public JawTbsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JawTbsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JawTbsService
     */
    @WebEndpoint(name = "JawTbsServiceImplPort")
    public JawTbsService getJawTbsServiceImplPort() {
        return super.getPort(new QName("http://service.webService.tcm.wondersgroup.com/", "JawTbsServiceImplPort"), JawTbsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JawTbsService
     */
    @WebEndpoint(name = "JawTbsServiceImplPort")
    public JawTbsService getJawTbsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webService.tcm.wondersgroup.com/", "JawTbsServiceImplPort"), JawTbsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAWTBSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw JAWTBSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return JAWTBSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
